import {ArrowUpRight,Phone,Check,ShieldCheck,Languages,MapPin} from 'lucide-react';
import {QuoteForm,FAQ} from '@/components/alamo';
import {SEO} from '@/components/seo';
import {agency,services} from '@/lib/content';
const heroImages:Record<string,{src:string;alt:string}>={
'seguro-sr22-fr44':{src:'/auto-sr22.webp',alt:'Consulta ilustrativa de un conductor con un agente sobre documentos de seguro'},
'seguro-licencia-internacional':{src:'/auto-licencia.webp',alt:'Conductora con una licencia extranjera junto a su automóvil'},
'seguro-auto-virginia':{src:'/auto-virginia.webp',alt:'Automóvil en una calle residencial del norte de Virginia'},
'seguro-auto-maryland':{src:'/auto-maryland.webp',alt:'Automóvil cerca del puerto y edificios históricos de Annapolis, Maryland'},
'seguro-auto-washington-dc':{src:'/auto-dc.webp',alt:'Automóvil en Washington DC con el Capitolio al fondo'}
};
export function AutoSitelinkPage({service}:{service:(typeof services)[number]}){const hero=heroImages[service.slug];return <main id="contenido" className="auto-landing auto-service-landing">
<SEO path={'/'+service.slug}/>
<section className="auto-landing-hero"><div className="wrap auto-landing-grid"><div className="auto-landing-copy"><div className="eyebrow"><MapPin size={16}/>{service.tag} · AGENCIA ALAMO</div><h1>{service.title}</h1><p>{service.intro}</p><div className="actions"><a className="btn" href="#cotizar-auto">Cotizar mi seguro <ArrowUpRight/></a><a className="btn white" href={agency.tel} data-event="call_click"><Phone/>703-256-1720</a></div><div className="auto-landing-trust"><span><Languages/>Atención bilingüe</span><span><Check/>Cotización sin compromiso</span><span><ShieldCheck/>15+ años en seguros</span></div></div><div className="auto-hero-photo"><div className="auto-hero-photo-crop"><img src={hero.src} alt={hero.alt} width="1200" height="900" fetchPriority="high"/></div></div></div></section>
<section className="section wrap"><div className="auto-heading"><div className="eyebrow">INFORMACIÓN PARA DECIDIR</div><h2>Entiende tus opciones antes de elegir.</h2></div><div className="auto-service-details">{service.sections.map(([title,text],i)=><article key={title}><span className="auto-service-number">0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div>{service.slug==='seguro-sr22-fr44'&&<p className="notice">Consulta la <a className="textlink" href="https://www.dmv.virginia.gov/businesses/insurance/certifications">información oficial del DMV de Virginia</a> sobre certificaciones. Los requisitos de tu caso deben verificarse con el DMV.</p>}</section>
<section className="auto-special"><div className="wrap auto-special-grid"><div><div className="eyebrow">ATENCIÓN PERSONAL EN ESPAÑOL</div><h2>Un agente te acompaña en el siguiente paso.</h2><p>Cuéntanos tu situación y revisemos coberturas, requisitos y opciones de pago. Te explicamos los detalles para que puedas decidir con claridad.</p><a className="btn" href="#cotizar-auto">Pedir una cotización <ArrowUpRight/></a></div><div><a href="/cotizar-seguro-auto"><h3>Compara opciones de seguro de auto ↗</h3><p>Revisa responsabilidad civil, colisión, cobertura comprensiva y servicios adicionales.</p></a><a href={agency.messenger} target="_blank" rel="noopener noreferrer" data-event="messenger_click"><h3>¿Prefieres enviar un mensaje? ↗</h3><p>Conversa con nuestro equipo por Messenger.</p></a></div></div></section>
<section className="auto-quote-section section"><div className="wrap auto-quote-grid"><div><div className="eyebrow">COTIZACIÓN SIN COMPROMISO</div><h2>Hablemos de tu seguro.</h2><p>Déjanos tus datos y un agente bilingüe te ayudará a revisar opciones según tu documentación, vehículo y estado.</p><a className="bigphone" href={agency.tel} data-event="call_click">703-256-1720</a><p>{agency.address}</p><p className="fineprint">La disponibilidad, elegibilidad y cobertura están sujetas a revisión y a las condiciones de la póliza. Una solicitud de cotización no activa cobertura.</p></div><div className="auto-landing-form" id="cotizar-auto"><QuoteForm/><p className="auto-form-note">¿Prefieres hablar? <a href={agency.tel}>Llama al 703-256-1720</a></p></div></div></section>
<nav className="wrap insurance-seo-links" aria-label="Otros seguros de auto"><h2>Más opciones para tu seguro de auto</h2><div>{services.filter(s=>s.slug!==service.slug&&['seguro-auto-virginia','seguro-auto-maryland','seguro-auto-washington-dc','seguro-sr22-fr44','seguro-licencia-internacional'].includes(s.slug)).map(s=><a href={'/'+s.slug} key={s.slug}>{s.title}</a>)}</div></nav><FAQ/>
</main>}
