import {pageMetadata,serviceSearch} from '@/lib/seo';
import {AutoSitelinkPage} from '@/components/auto-sitelink-page';
import {notFound} from 'next/navigation';
import {services,agency} from '@/lib/content';
import {Actions,Contact,FAQ} from '@/components/alamo';
import {SEO} from '@/components/seo';
import {origin} from '@/lib/config';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const s=services.find(s=>s.slug===slug);return s?pageMetadata({...serviceSearch[slug],path:'/'+slug}):{title:'Página no encontrada',robots:{index:false,follow:false}}}
export default async function Service({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const s=services.find(s=>s.slug===slug);if(!s)notFound();if(['seguro-sr22-fr44','seguro-licencia-internacional','seguro-auto-virginia','seguro-auto-maryland','seguro-auto-washington-dc'].includes(slug))return <AutoSitelinkPage service={s}/>;const isContractor=slug==='seguro-comercial-contratistas';return <main id="contenido"><SEO path={'/'+slug}/><section className={`innerhero${isContractor?' commercial-photo-hero':''}`}><div className={`wrap${isContractor?' commercial-photo-hero-grid':''}`}><div className={isContractor?'commercial-hero-copy':undefined}><div className="breadcrumb"><a href="/">Inicio</a> / Seguros</div><div className="eyebrow">{s.tag}</div><h1>{s.title}</h1><p>{s.intro}</p><Actions/></div>{isContractor&&<div className="auto-hero-photo commercial-hero-photo"><div className="auto-hero-photo-crop"><img src="/seguro-negocio.webp" alt="Contratistas trabajando en un proyecto de pavimentación" width="1000" height="700" fetchPriority="high"/></div></div>}</div></section><div className="section wrap article-grid"><article className="prose">{s.sections.map(([h,p])=><section key={h}><h2>{h}</h2><p>{p}</p></section>)}{slug==='seguro-sr22-fr44'&&<p className="notice">Consulta la <a className="textlink" href="https://www.dmv.virginia.gov/businesses/insurance/certifications">información oficial del DMV de Virginia</a> sobre certificaciones. Los requisitos de tu caso deben verificarse con el DMV.</p>}<p className="notice">La disponibilidad, elegibilidad y cobertura están sujetas a revisión y a las condiciones de la póliza. Una solicitud de cotización no activa cobertura.</p></article><aside className="side-card"><h3>Hablemos de tu seguro.</h3><p>Un agente bilingüe te ayuda a entender tus opciones.</p><a className="btn" href="/#cotizar">Pide tu cotización</a><a className="btn outline" href={agency.tel}>Llama al 703-256-1720</a><a className="btn outline" href={agency.messenger}>Enviar mensaje</a></aside></div><Contact/><FAQ/></main>}
