import {pageMetadata} from '@/lib/seo';
import type {Metadata} from 'next';
import {ArrowUpRight,Phone,Check,ShieldCheck,Car,Languages,MapPin} from 'lucide-react';
import {QuoteForm} from '@/components/alamo';
import {SEO} from '@/components/seo';
import {agency} from '@/lib/content';
import {origin} from '@/lib/config';
const path='/cotizar-seguro-auto';
export const metadata:Metadata=pageMetadata({title:'Cotiza Seguro de Auto en Español | VA, MD y DC',description:'Compara opciones de seguro de auto con Agencia Alamo. Cotización en español, SR-22, FR-44 y licencia internacional. Llama al 703-256-1720.',path,image:'/auto-cotizar.webp'});
const questions=[
['¿Cómo encuentro un seguro de auto económico?','Compara propuestas con los mismos límites, deducibles y período de cobertura. Un agente puede revisar descuentos y opciones de pago según tu situación. No garantizamos una tarifa ni un ahorro específico.'],
['¿Puedo cotizar con licencia extranjera o internacional?','Sí, puedes consultar. La aceptación depende de la documentación, el estado y las reglas de la aseguradora. Un permiso internacional no sustituye por sí solo una licencia válida.'],
['¿Me ayudan con SR-22 o FR-44 en Virginia?','Sí. Comparte la notificación del DMV con el agente para revisar el requisito y buscar opciones. Son certificaciones de responsabilidad financiera, no coberturas adicionales; comprar una póliza no restablece automáticamente la licencia.'],
['¿Qué significa cobertura completa o full coverage?','Se usa habitualmente para referirse a una combinación de responsabilidad civil, colisión y cobertura comprensiva. No es un término que garantice protección contra todo: revisa límites, deducibles y exclusiones de la propuesta.'],
['¿Puedo incluir grúa y auto rentado?','Consulta por asistencia en carretera y reembolso de alquiler de vehículo. Su disponibilidad, límites y condiciones dependen de la compañía y la póliza.'],
['¿Qué necesito para cotizar mi seguro de carro?','Ten a mano información del vehículo, conductores, domicilio y póliza actual si tienes una. En el formulario inicial deja tus datos de contacto; el agente te indicará cómo compartir documentos.'],
['¿Atienden a conductores casados y solteros?','Sí. La cotización considera los datos reales de los conductores y otros factores de la aseguradora. Consulta descuentos por seguro previo y otras opciones para las que puedas calificar.']
];
export default function AutoLanding(){return <main id="contenido" className="auto-landing">
<SEO path={path} faq={questions}/>
<section className="auto-landing-hero"><div className="wrap auto-landing-grid"><div className="auto-landing-copy"><div className="eyebrow"><MapPin size={16}/> ANNANDALE · VIRGINIA · MARYLAND · DC</div><h1>Tu seguro de auto.<br/><span>En español.<br/>Sin tantas dudas.</span></h1><p>Compara opciones para proteger tu carro con Agencia Alamo, tu agencia independiente de seguros en Annandale, Virginia.</p><div className="actions"><a className="btn" href="#cotizar-auto">Cotizar mi seguro <ArrowUpRight/></a><a className="btn white" href={agency.tel} data-event="call_click"><Phone/>703-256-1720</a></div><div className="auto-landing-trust"><span><Languages/>Atención bilingüe</span><span><Check/>Cotización sin compromiso</span><span><ShieldCheck/>15+ años en seguros</span></div></div><div className="auto-hero-photo"><div className="auto-hero-photo-crop"><img src="/auto-cotizar.webp" alt="Pareja junto a su automóvil en una escena ilustrativa de seguro de auto" width="1200" height="900" fetchPriority="high"/></div></div></div></section>
<section className="section wrap"><div className="auto-heading"><div className="eyebrow">PRECIO Y PROTECCIÓN</div><h2>Busca un seguro de auto económico con coberturas que entiendas.</h2><p>La mensualidad es solo una parte. Te ayudamos a comparar el costo total, el pago inicial, los límites y los deducibles de cada cotización de seguro de carro.</p></div><div className="auto-detail-grid">{[
['Responsabilidad civil','Revisa protección ante reclamaciones por lesiones o daños a terceros, según los límites y condiciones de la póliza.'],
['Colisión y cobertura comprensiva','Consulta opciones para daños al vehículo por colisión y otros eventos cubiertos. Si buscas full coverage, revisemos qué incluye exactamente tu propuesta.'],
['Grúa y auto rentado','Pregunta por asistencia en carretera y reembolso de alquiler mientras se repara tu vehículo por un siniestro cubierto.'],
['Descuentos y formas de pago','Consulta descuentos por seguro previo y otras opciones disponibles. Cotizamos con los datos reales de tus conductores, casados o solteros.']
].map(([t,d])=><article key={t}><Car/><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="auto-special"><div className="wrap auto-special-grid"><div><div className="eyebrow">OPCIONES SEGÚN TU SITUACIÓN</div><h2>Un nuevo comienzo al volante.</h2><p>¿Compraste un carro, subió tu renovación o necesitas revisar una certificación? Conversemos antes de elegir tu próxima póliza.</p><a className="btn" href="#cotizar-auto">Pedir una cotización <ArrowUpRight/></a></div><div><a href="/seguro-sr22-fr44"><h3>Seguro SR-22 y FR-44 en Virginia ↗</h3><p>Te ayudamos a revisar el requisito del DMV y buscar opciones según tu caso.</p></a><a href="/seguro-licencia-internacional"><h3>Seguro con licencia internacional o extranjera ↗</h3><p>Consulta opciones según tu documentación y el estado donde resides.</p></a></div></div></section>
<section className="section wrap"><div className="auto-heading"><div className="eyebrow">ASÍ DE SENCILLO</div><h2>De la consulta a una decisión informada.</h2></div><ol className="auto-steps"><li><b>01</b><h3>Cuéntanos qué necesitas</h3><p>Deja tus datos o llama. Indica dónde vives y qué vehículo quieres asegurar.</p></li><li><b>02</b><h3>Revisa tus opciones</h3><p>Un agente te explica las propuestas, coberturas, pagos y descuentos disponibles.</p></li><li><b>03</b><h3>Elige con claridad</h3><p>Confirma los términos y la fecha de inicio antes de cancelar tu seguro actual.</p></li></ol></section>
<section className="auto-quote-section section"><div className="wrap auto-quote-grid"><div><div className="eyebrow">COTIZACIÓN SIN COMPROMISO</div><h2>Ahora sí, hablemos de tu seguro.</h2><p>Déjanos tus datos y un agente bilingüe te ayudará a comparar opciones para tu vehículo.</p><a className="bigphone" href={agency.tel} data-event="call_click">703-256-1720</a><p>Atención en español e inglés.</p></div><div className="auto-landing-form" id="cotizar-auto"><QuoteForm/><p className="auto-form-note">¿Prefieres hablar? <a href={agency.tel}>Llama al 703-256-1720</a></p></div></div></section>
<section className="auto-faq section"><div className="wrap"><div className="auto-heading"><h2>Preguntas sobre tu seguro de auto</h2></div><div className="auto-faq-list">{questions.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>
<section className="section wrap auto-local"><div><div className="eyebrow">TU AGENCIA CERCA DE TI</div><h2>Seguro de auto en Annandale y el norte de Virginia.</h2><p>Atendemos a conductores de Annandale, Falls Church, Fairfax, Arlington, Alexandria y Springfield. También recibimos consultas de seguro de auto en Maryland, Washington DC y Delaware.</p><p><b>Alamo Insurance Agency · Agencia Alamo</b><br/>{agency.address}</p><a className="textlink" href={agency.map} target="_blank" rel="noopener noreferrer">Cómo llegar a la oficina <ArrowUpRight/></a></div><div className="auto-final-card"><h2>Hablemos de tu carro.</h2><p>Atención personal en español e inglés.</p><a className="btn" href={agency.tel} data-event="call_click"><Phone/>703-256-1720</a><a className="textlink" href="#cotizar-auto">Solicitar mi cotización <ArrowUpRight/></a><p className="fineprint">La disponibilidad, cobertura, descuentos y elegibilidad dependen del estado y la aseguradora. Solicitar una cotización no activa cobertura.</p></div></section>
<nav className="wrap insurance-seo-links" aria-label="Guías de seguro de auto"><h2>Opciones según tu estado y documentación</h2><div><a href="/seguro-auto-virginia">Seguro de auto en Virginia</a><a href="/seguro-auto-maryland">Seguro de auto en Maryland</a><a href="/seguro-auto-washington-dc">Seguro de auto en Washington DC</a><a href="/seguro-sr22-fr44">SR-22 y FR-44 en Virginia</a><a href="/seguro-licencia-internacional">Seguro con licencia internacional</a></div></nav></main>}
